### ISSUE TITLE
CharcountedTextarea $refs.countInput is undefined

### ISSUE THREAD

**Issue by NLDevX** [martin-ro/filament-charcount-field#3]
First i want to thank you for your work.
CharcountedTextInput is working very well but CharcountedTextarea is not working and it say that:

- **$refs.countInput is undefined**
- **color is not defined**
- **count is not defined**
- **Error: request failed with status 404**

After debugging i found what cause the problem and i wanna suggest you to refactor and correct this part:

```blade
@if ($shouldAutosize())
      x-data="textareaFormComponent()"
      x-on:input="render()"
      style="height: 150px"
      {{ $getExtraAlpineAttributeBag() }}
@endif
```

Good luck.

**Comment by martin-ro** [comment]
Hi, I will do a refactor and tag a stable release of the package sometime soon and then probably merge this. Thank you.

**Comment by martin-ro** [comment]
Check the latest version and let me know if that resolves the issue

cheers
