### ISSUE TITLE
Closures available?

### ISSUE THREAD

**Issue by DaedalusWings** [martin-ro/filament-charcount-field#8]
Is there a possibility to use closures for example in CharcountedTextarea->maxCharacters like this. Or do you plan to integrate this feature?
```
CharcountedTextarea::make('conclusion')
    ->label('Fazit')
    ->rows(2)
    ->maxCharacters(function (Closure $get) {
        if ($get('department_id') == 102) {
            return 225;
        } else {
            return 170;
        }
    })
```

**Comment by martin-ro** [comment]
It's not possible at the moment but should be easy to integrate. I currently wait for v3 release before continuing to work on this package.
